### ISSUE TITLE
List all routes in app

### ISSUE THREAD

**Issue by pronebird** [labithiotis/express-list-routes#1]
I use bunch of routers in my express 4 app and I'd like to list all routes in app. Is it possible to achieve this with express-list-routes?

**Comment by labithiotis** [comment]
Yer, just call it multiply times:

``` javascript
expressListRoutes({ prefix: '/api/v1' }, 'Version1:', router1 );
expressListRoutes({ prefix: '/api/v2' }, 'Version2:', router2 );
```

**Comment by pronebird** [comment]
Thanks, that was obvious, I thought I could just pass express app and get all routes printed. Does not seem to be possible with Express 4.0 at all...
