### ISSUE TITLE
Unnecessary prefix on Windows

### ISSUE THREAD

**Issue by nartos9090** [labithiotis/express-list-routes#15]
In windows OS, the log will shows file path instead of just route path

```
GET      D:\my-route
Example app listening on port 3000
```

Probably because of `path.resolve``` before the log

**Comment by ElenaChes** [comment]
Same happens on my end, it'll write the folder path and then add whatever the route path is...
`expressListRoutes(app, { spacer: 2, prefix: "http://localhost:8080/" });` gives:
```
GET  F:\GitHub\project\http:\localhost:8080\userTest
GET  F:\GitHub\project\http:\localhost:8080\example\text
GET  F:\GitHub\ptoject\http:\localhost:8080\example\2
```
`expressListRoutes(router);` gives:
```
GET      F:\userTest
GET      F:\example
GET      F:\example\text
GET      F:\example\2
```

**Comment by labithiotis** [comment]
@nartos9090 @ElenaChes I have updated the code (v1.1.5) to use `path.normalize` which should resolve your issues on windows machines.
