### ISSUE TITLE
suppress logger

### ISSUE THREAD

**Issue by easmithdev** [labithiotis/express-list-routes#19]
Hello. I firstly want to thank you for creating this. It's quite helpful. 
I have a question regarding the logger. Is there a way to not send logs to console? Basically turn off the logger.

**Comment by gilbertgit95** [comment]
> 

On my end, I pass empty function on the option logger
expressListRoutes(appRoute, {
    logger: () => {}
})

**Comment by gilbertgit95** [comment]
On my end, I just pass an empty function to the option.logger
expressListRoutes(appRoute, {
            logger: () => {}
})

**Comment by easmithdev** [comment]
Thanks, @gilbertgit95 That is exactly what I was looking for. Greatly appreciated 👍🏾

**Comment by easmithdev** [comment]
@gilbertgit95  provided a solution to suppressing the logger.
