### ISSUE TITLE
[feature request] Add NestJS usage

### ISSUE THREAD

**Issue by angelhdzmultimedia** [labithiotis/express-list-routes#23]
Happy new year! 🎉

Excellent package! Thanks to the team. 🔥👏

This time I want to submit a feature request:

Add NestJS usage.

` expressListRoutes(app.getHttpAdapter().getInstance())`

Also add a note on importing it like `import expressListRoutes from 'express-list-routes'` 
by enabling `esModuleInterop` in `tsconfig.json` of a NestJS app.

**Comment by labithiotis** [comment]
@angelhdzmultimedia Happy New Year 🎉 

I am curious what the request is exactly, as passing in the express instance should still spit out logs of routes used by the express application. What may be happening if the nestJS routes are registered dynamically so you should only invoke expressListRoutes after nestJS has registered all routes? 

Which you could do with a custom NestJS module
```ts
@Injectable()
export class RouteLogging implements OnApplicationBootstrap {
    onApplicationBootstrap() {
      // You may be able to inject the app/adapter into this module too
      expressListRoutes(app.getHttpAdapter().getInstance())
    }
}
```

I will look at adding a small FAQ to the readme to mention enabling esModuleInterop. I would like to explore refactoring this to be TS natively and using rollup to compile JS
