### ISSUE TITLE
not working in v5

### ISSUE THREAD

**Issue by tuke307** [labithiotis/express-list-routes#25]
error:

Cannot read properties of undefined (reading 'toString')

**Comment by labithiotis** [comment]
@tuke307 Ok, I will have to look into it, the tests were using alpha (npm:express@^5.0.0-alpha.8) so maybe something changed.

**Comment by labithiotis** [comment]
@tuke307 Should work for express5 again, the nested route path name will not though as exp5 doesn't include that info :(

**Comment by tuke307** [comment]
@labithiotis thank you very much! Amazingly fast!
