### ISSUE TITLE
Nested routers are not handled?

### ISSUE THREAD

**Issue by pronebird** [labithiotis/express-list-routes#3]
It does not seem to handle nested routers.

**Comment by labithiotis** [comment]
Can you give me an example of nested routers. 

You can pass each router as additional params i.e. `expressListRoutes(routerA, routerB, routerC)`

**Comment by pronebird** [comment]
You can mount apps to each other in Express 4, so I guess I would have to extract all of them.

**Comment by labithiotis** [comment]
It's been a year since I touched this :worried:, I will have to have a look at the router and see how and/or if they include reference to mounted expresses.

Can you share some snippets of how you have them mounted so I can replicate exactly ?

**Comment by pronebird** [comment]
Sure you can find it in documentation too:

``` js
var express = require('express');
var expressListRoutes = require('express-list-routes');

var app = express(); // the main app
var admin = express(); // the sub app

app.get('/', function (req, res) {
  res.send('Index Homepage');
});

admin.get('/', function (req, res) {
  console.log(admin.mountpath); // /admin
  res.send('Admin Homepage');
});

app.use('/admin', admin); // mount the sub app

// expecting it to print the whole hierarchy
expressListRoutes(app._router);
```

I skimmed through but I couldn't find any way to actually enumerate linked apps. I think we would have to use private properties to achieve this.

**Comment by labithiotis** [comment]
Great, thank you, I'll look into it. I can't promise to have anything soon for this though :(

In the meantime you can do this `expressListRoutes(app._router, admin._router);`

**Comment by pronebird** [comment]
Sure, not critical.

**Comment by sazzer** [comment]
Just hit this myself, and spent a while trying to work out why my routers weren't working correctly before thinking to actually try it with cURL and see...
