### ISSUE TITLE
Support custom logger

### ISSUE THREAD

**Issue by joeyfigaro** [labithiotis/express-list-routes#8]
Thank you for authoring this! It is very helpful. It'd be awesome if you supported a custom logger / overriding the method used for logging.

**Comment by labithiotis** [comment]
@joeyfigaro thanks for the suggestion, it wouldn't be too tricky to add, I just need time to do it 😉  - I'll see what I can do

**Comment by labithiotis** [comment]
@joeyfigaro Created a PR, see if that satisfies your use case https://github.com/labithiotis/express-list-routes/pull/9/files
